/**
 * Approximates the Figma `NOISE` effect on the hero (monotone, size 2, density
 * 0.3, black at 50%).
 *
 * There is no CSS equivalent, so the grain is generated by an inline SVG
 * `feTurbulence` filter held in `--texture-noise` — no network request, no
 * binary asset in the repository. Against #1A1A1A the difference from Figma's
 * own renderer is not perceptible.
 */
export function Noise({ className = '' }: { className?: string }) {
  return (
    <div
      aria-hidden="true"
      className={`pointer-events-none absolute inset-0 -z-10 bg-[image:var(--texture-noise)] bg-repeat opacity-[0.18] mix-blend-soft-light ${className}`}
    />
  )
}
